### PR TITLE
:card_index: Fix leaky event registration

### LINKED ISSUE #6: Possible scroll handler leak
This line removes the _onScroll method:
https://github.com/samccone/scrollin/blob/master/index.js#L41

This line adds a _throttled_ _onScroll method:
https://github.com/samccone/scrollin/blob/master/index.js#L49

Will the _onScroll handler never die since the function registered isn't the function deregistered?

### PR DESCRIPTION
**Pull request by samccone**
This arose because of the change introduced in
e9e94314a99c79e550afef3753c05371f54b274d

Fixes #6
Thanks @ianmstew

### CODE REVIEW

**Comment by ianmstew** [comment]
:smile:

**Comment by wkf** [comment]
Looks pretty good :+1:

**Comment by wkf** [comment]
:shaved_ice:

**Comment by wkf** [comment]
:crumpet:

**Comment by samccone** [comment]
landed in 0.1.5

**Pull request closed without merging**
