### PR TITLE
Issue#12 - Add the ability to pass in a Nodelist into track

### PR DESCRIPTION
**Pull request by davesnx**
Hello @samccone 

Small PR for improve a little bit the interface for receive an array of `DOMElements`, and a few tests for testing it.

I use concat, instead of other methods for simplicity and for not verbose it.

ps. I will contribute a few more in this repo, what do you think about add `sinon` for create some spy on the tests?

### CODE REVIEW

**Comment by samccone** [comment]
fixes #12

**Comment by samccone** [comment]
hi @davesnx thanks for the PR! :sparkles: 

I have left you some feedback, for now adding sinon seems unneeded however if you think it will improve the test suite I would be interested in seeing a proposal from you.

Thanks! :space_invader:

**Comment by samccone** [comment]
no need to commit the dist on each commit :) I will cut that when I do a release... it also looks like some tests are failing now

**Comment by davesnx** [comment]
Fixed @samccone. Was a fast commit without running the tests :cry:
Removed the dist/ folder also.

**Comment by davesnx** [comment]
@samccone Should be merged? ;3

**Comment by samccone** [comment]
:+1: yeppp :)

**Comment by samccone** [comment]
manually landed! thx!

v0.4.0

**Pull request closed without merging**
